// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ReactJsComponentGen from "./ReactJsComponent.gen";

var make = ReactJsComponentGen.default;

export {
  make ,
  
}
/* make Not a pure module */
